apiVersion: v1
kind: Service
metadata:
  name: django-4
  labels:
    app: ansible-gce-demo-247311
spec:
  ports:
    - port: 3000
  selector:
    app: ansible-gce-demo-247311
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gce-comments-4
  labels:
    app: ansible-gce-demo-247311
spec:
  selector:
    matchLabels:
      app: ansible-gce-demo-247311
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ansible-gce-demo-247311
        tier: frontend
    spec:
      containers:
      - image: gcr.io/ansible-gce-demo-247311/comments:0.0.3
        name: ansible-gce-demo-247311
        ports:
        - containerPort: 3000
          name: ansible
